#!/usr/bin/env bash
# ------------------------------------------------------------------
# Servagent - Generate OAuth registration credentials
#
# Generates a CLIENT_ID and CLIENT_SECRET for protecting /mcp/register.
# Outputs the values and optionally writes them to the .env file.
#
# Usage:
#   bash generate-oauth-credentials.sh              # Print credentials
#   bash generate-oauth-credentials.sh --write      # Write to .env
#   bash generate-oauth-credentials.sh --write /path/to/.env
# ------------------------------------------------------------------
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }

# --- Parse arguments ---
WRITE=false
ENV_FILE=""

for arg in "$@"; do
    case "$arg" in
        --write) WRITE=true ;;
        --*)     echo "Unknown option: $arg"; exit 1 ;;
        *)       ENV_FILE="$arg" ;;
    esac
done

# Default .env path
if [[ -z "$ENV_FILE" ]]; then
    # Check common locations
    if [[ -f "/opt/servagent/.env" ]]; then
        ENV_FILE="/opt/servagent/.env"
    elif [[ -f "$(dirname "${BASH_SOURCE[0]}")/.env" ]]; then
        ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.env"
    else
        ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.env"
    fi
fi

# --- Generate credentials ---
# Use Python (available since servagent requires it)
if command -v python3 &>/dev/null; then
    PYTHON=python3
elif command -v python &>/dev/null; then
    PYTHON=python
else
    echo "Error: Python not found. Install Python 3.10+ first." >&2
    exit 1
fi

CLIENT_ID=$($PYTHON -c "import secrets; print('servagent-' + secrets.token_hex(8))")
CLIENT_SECRET=$($PYTHON -c "import secrets; print(secrets.token_urlsafe(48))")

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}        OAuth Registration Credentials                    ${CYAN}║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}                                                          ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}  CLIENT_ID:     ${GREEN}${CLIENT_ID}${NC}"
echo -e "${CYAN}║${NC}  CLIENT_SECRET: ${GREEN}${CLIENT_SECRET}${NC}"
echo -e "${CYAN}║${NC}                                                          ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

if $WRITE; then
    if [[ ! -f "$ENV_FILE" ]]; then
        warn "File not found: $ENV_FILE"
        warn "Create it first (cp .env.example .env) or specify the path:"
        warn "  bash generate-oauth-credentials.sh --write /path/to/.env"
        exit 1
    fi

    # Check if variables already exist (uncommented)
    if grep -q "^SERVAGENT_OAUTH_CLIENT_ID=" "$ENV_FILE" 2>/dev/null; then
        warn "SERVAGENT_OAUTH_CLIENT_ID already set in $ENV_FILE"
        warn "Remove the existing lines first, or edit manually."
        exit 1
    fi

    # Append or replace commented lines
    if grep -q "^# SERVAGENT_OAUTH_CLIENT_ID=" "$ENV_FILE" 2>/dev/null; then
        # Replace commented lines with actual values
        sed -i.bak \
            -e "s|^# SERVAGENT_OAUTH_CLIENT_ID=.*|SERVAGENT_OAUTH_CLIENT_ID=${CLIENT_ID}|" \
            -e "s|^# SERVAGENT_OAUTH_CLIENT_SECRET=.*|SERVAGENT_OAUTH_CLIENT_SECRET=${CLIENT_SECRET}|" \
            "$ENV_FILE"
        rm -f "${ENV_FILE}.bak"
    else
        # Append to the file
        cat >> "$ENV_FILE" <<EOF

# OAuth registration credentials (generated by generate-oauth-credentials.sh)
SERVAGENT_OAUTH_CLIENT_ID=${CLIENT_ID}
SERVAGENT_OAUTH_CLIENT_SECRET=${CLIENT_SECRET}
EOF
    fi

    info "Written to ${ENV_FILE}"
    echo ""
fi

# --- Usage instructions ---
echo -e "Add to your ${CYAN}.env${NC} file:"
echo ""
echo "  SERVAGENT_OAUTH_CLIENT_ID=${CLIENT_ID}"
echo "  SERVAGENT_OAUTH_CLIENT_SECRET=${CLIENT_SECRET}"
echo ""
echo -e "Test registration with ${CYAN}curl${NC}:"
echo ""
echo "  curl -X POST https://your-server.com/mcp/register \\"
echo "    -u \"${CLIENT_ID}:${CLIENT_SECRET}\" \\"
echo "    -H \"Content-Type: application/json\" \\"
echo "    -d '{\"redirect_uris\":[\"http://localhost/callback\"],\"client_name\":\"My App\"}'"
echo ""
