#!/usr/bin/env bash
# ------------------------------------------------------------------
# Servagent - Add HTTPS to an existing installation
#
# Usage:
#   sudo bash setup-tls.sh votre-domaine.com
#
# Detects Nginx automatically:
#   Nginx running → webroot challenge + Nginx reverse proxy
#   No Nginx      → standalone challenge + built-in TLS on port 443
# ------------------------------------------------------------------
set -euo pipefail

APP_NAME="servagent"
APP_DIR="/opt/${APP_NAME}"
VENV_DIR="${APP_DIR}/.venv"
ENV_FILE="${APP_DIR}/.env"
SERVICE_USER="servagent"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# --- Validate ---
DOMAIN="${1:-}"
[[ -z "$DOMAIN" ]] && error "Usage: sudo bash setup-tls.sh <your-domain.com>"
[[ $EUID -ne 0 ]] && error "This script must be run as root (use sudo)."
[[ ! -f "$ENV_FILE" ]] && error "Servagent not installed. Run install.sh first."

# Detect Nginx
NGINX_ACTIVE=false
if systemctl is-active --quiet nginx 2>/dev/null; then
    NGINX_ACTIVE=true
    info "Nginx detected — will use Nginx reverse proxy mode."
else
    info "Nginx not detected — will use built-in TLS on port 443."
fi

# Detect Nginx config directory layout
detect_nginx_conf() {
    if [[ -d /etc/nginx/sites-available ]]; then
        NGINX_CONF="/etc/nginx/sites-available/${APP_NAME}.conf"
        NGINX_LINK="/etc/nginx/sites-enabled/${APP_NAME}.conf"
        NGINX_STYLE="sites"
    else
        mkdir -p /etc/nginx/conf.d
        NGINX_CONF="/etc/nginx/conf.d/${APP_NAME}.conf"
        NGINX_LINK=""
        NGINX_STYLE="confd"
    fi
}

enable_nginx_conf() {
    if [[ "$NGINX_STYLE" == "sites" ]]; then
        ln -sf "${NGINX_CONF}" "${NGINX_LINK}"
    fi
    nginx -t && systemctl reload nginx
}

# --- Install certbot ---
if ! command -v certbot &>/dev/null; then
    info "Installing certbot..."
    if command -v apt-get &>/dev/null; then
        if $NGINX_ACTIVE; then
            apt-get update -qq && apt-get install -y -qq certbot python3-certbot-nginx
        else
            apt-get update -qq && apt-get install -y -qq certbot
        fi
    elif command -v dnf &>/dev/null; then
        dnf install -y -q certbot
    elif command -v yum &>/dev/null; then
        yum install -y -q certbot
    else
        error "Could not install certbot. Install it manually: https://certbot.eff.org"
    fi
else
    info "certbot already installed."
fi

CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"

if $NGINX_ACTIVE; then
    # =================================================================
    # MODE A: Nginx running → webroot + reverse proxy
    # =================================================================
    WEBROOT="/var/www/certbot"
    mkdir -p "${WEBROOT}"

    # Detect Nginx config layout and create temp config
    detect_nginx_conf
    cat > "${NGINX_CONF}" <<NGINX
server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
NGINX
    enable_nginx_conf

    # Obtain certificate
    if [[ ! -d "$CERT_DIR" ]]; then
        info "Requesting certificate for ${DOMAIN}..."
        certbot certonly \
            --webroot \
            --webroot-path "${WEBROOT}" \
            --non-interactive \
            --agree-tos \
            --register-unsafely-without-email \
            --domain "${DOMAIN}"
    else
        info "Certificate already exists for ${DOMAIN}."
    fi

    [[ ! -f "${CERT_DIR}/fullchain.pem" ]] && error "Certificate not found at ${CERT_DIR}/fullchain.pem"
    info "Certificate OK."

    # Full Nginx config with TLS + reverse proxy
    cat > "${NGINX_CONF}" <<NGINX
# Servagent — Nginx reverse proxy with TLS
# Auto-generated by setup-tls.sh

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # Proxy all MCP endpoints: /mcp (streamable-http), /sse, /messages/
    location / {
        proxy_pass http://127.0.0.1:8765;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding on;
        proxy_read_timeout 300s;
    }
}

server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
NGINX
    enable_nginx_conf
    info "Nginx reverse proxy configured."

    # MCP stays on 127.0.0.1:8765
    sed -i 's/^SERVAGENT_HOST=.*/SERVAGENT_HOST=127.0.0.1/' "$ENV_FILE"
    # Remove any built-in TLS config
    sed -i '/^SERVAGENT_TLS_CERTFILE=/d' "$ENV_FILE"
    sed -i '/^SERVAGENT_TLS_KEYFILE=/d' "$ENV_FILE"

    # Renewal hook: reload Nginx
    cat > /etc/systemd/system/certbot-renew-mcp.service <<EOF
[Unit]
Description=Certbot renewal for Servagent

[Service]
Type=oneshot
ExecStart=/usr/bin/certbot renew --quiet --deploy-hook "systemctl reload nginx"
EOF

else
    # =================================================================
    # MODE B: No Nginx → standalone + built-in TLS
    # =================================================================
    info "Stopping ${APP_NAME} temporarily..."
    systemctl stop "${APP_NAME}" 2>/dev/null || true

    if [[ ! -d "$CERT_DIR" ]]; then
        info "Requesting certificate for ${DOMAIN} (port 80 must be free)..."
        certbot certonly \
            --standalone \
            --non-interactive \
            --agree-tos \
            --register-unsafely-without-email \
            --domain "${DOMAIN}" \
            --preferred-challenges http
    else
        info "Certificate already exists for ${DOMAIN}."
    fi

    [[ ! -f "${CERT_DIR}/fullchain.pem" ]] && error "Certificate not found at ${CERT_DIR}/fullchain.pem"
    info "Certificate OK."

    # Grant read access
    if ! getent group certkeys &>/dev/null; then
        groupadd certkeys
    fi
    usermod -aG certkeys "${SERVICE_USER}"
    chown root:certkeys "${CERT_DIR}/privkey.pem"
    chmod 640 "${CERT_DIR}/privkey.pem"
    chmod 750 /etc/letsencrypt/live /etc/letsencrypt/archive
    chown root:certkeys /etc/letsencrypt/live /etc/letsencrypt/archive

    # Update .env
    sed -i '/^SERVAGENT_PORT=/d' "$ENV_FILE"
    sed -i '/^SERVAGENT_TLS_CERTFILE=/d' "$ENV_FILE"
    sed -i '/^SERVAGENT_TLS_KEYFILE=/d' "$ENV_FILE"
    sed -i 's/^SERVAGENT_HOST=.*/SERVAGENT_HOST=0.0.0.0/' "$ENV_FILE"
    cat >> "$ENV_FILE" <<EOF
SERVAGENT_PORT=443
SERVAGENT_TLS_CERTFILE=${CERT_DIR}/fullchain.pem
SERVAGENT_TLS_KEYFILE=${CERT_DIR}/privkey.pem
EOF

    # Allow port 443 binding
    REAL_PYTHON=$(readlink -f "${VENV_DIR}/bin/python3")
    setcap 'cap_net_bind_service=+ep' "$REAL_PYTHON" 2>/dev/null || \
        warn "setcap failed — the service may need to run as root for port 443."

    # Renewal hook: restart server
    cat > /etc/systemd/system/certbot-renew-mcp.service <<EOF
[Unit]
Description=Certbot renewal for Servagent

[Service]
Type=oneshot
ExecStart=/usr/bin/certbot renew --quiet --deploy-hook "systemctl restart ${APP_NAME}"
EOF
fi

# --- Renewal timer ---
cat > /etc/systemd/system/certbot-renew-mcp.timer <<EOF
[Unit]
Description=Twice-daily certbot renewal check

[Timer]
OnCalendar=*-*-* 02,14:30:00
RandomizedDelaySec=3600
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now certbot-renew-mcp.timer

# --- Restart server ---
info "Restarting ${APP_NAME}..."
systemctl restart "${APP_NAME}"

echo ""
info "============================================="
info " TLS setup complete!"
info " Endpoint: https://${DOMAIN}/mcp"
if $NGINX_ACTIVE; then
    info " Mode: Nginx reverse proxy"
else
    info " Mode: Built-in TLS (port 443)"
fi
info " Certificate auto-renews every 12 hours."
info "============================================="
echo ""
warn "Make sure ports 80 and 443 are open in your firewall:"
warn "  ufw allow 80/tcp && ufw allow 443/tcp"
